tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/services"
tap "stripe/stripe-cli"
brew "awscli"
brew "bat"
brew "black"
brew "cmake"
brew "ruby"
brew "cocoapods"
brew "coreutils"
brew "curl"
brew "duti"
brew "eslint"
brew "exiftool"
brew "eza"
brew "gnutls"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "fswatch"
brew "fzf"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "git-lfs"
brew "go"
brew "graphviz"
brew "pkgconf"
brew "imagemagick"
brew "ispell"
brew "jq"
brew "krb5"
brew "libagg"
brew "mas"
brew "mkcert"
brew "nvm"
brew "parallel"
brew "pipx"
brew "pnpm"
brew "pre-commit"
brew "prettier"
brew "prettyping"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "shellcheck"
brew "the_silver_searcher"
brew "trash", link: true
brew "tree"
brew "uv"
brew "vercel-cli"
brew "vips"
brew "watchman"
brew "wget"
brew "z"
brew "zlib", link: true
brew "zsh-autosuggestions"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-modern-purple-flat-icon"]
brew "stripe/stripe-cli/stripe"
cask "bartender"
cask "chatgpt"
cask "cleanshot"
cask "daisydisk"
cask "font-fira-code"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "granola"
cask "itsycal"
cask "linear-linear"
cask "orbstack"
cask "raycast"
cask "rectangle"
cask "slack"
cask "steam"
cask "zoom"
mas "Flighty", id: 1358823008
mas "Hue in the Menu", id: 1534707384
mas "Keynote", id: 409183694
mas "Mini Motorways", id: 1456188526
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Strongbox", id: 1270075435
mas "Xcode", id: 497799835
