tap "brewsci/bio"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/services"
tap "render-oss/render"
brew "python@3.11"
brew "awscli"
brew "bat"
brew "black"
brew "blast"
brew "cmake"
brew "coreutils"
brew "cruft"
brew "curl"
brew "doctl"
brew "eslint"
brew "exiftool"
brew "eza"
brew "ruby"
brew "tesseract"
brew "ffmpeg"
brew "fswatch"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "git-lfs"
brew "go"
brew "librsvg"
brew "graphviz"
brew "imagemagick"
brew "ipfs"
brew "ispell"
brew "jpeg"
brew "jq"
brew "krb5"
brew "mas"
brew "minimap2"
brew "neofetch"
brew "nvm"
brew "pandoc"
brew "pipx"
brew "pnpm"
brew "postgresql@14"
brew "pre-commit"
brew "prettier"
brew "prettyping"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "samtools"
brew "shellcheck"
brew "swift-format"
brew "the_silver_searcher"
brew "trash"
brew "tree"
brew "uv"
brew "vercel-cli"
brew "virtualenv"
brew "watchman"
brew "wget"
brew "yarn"
brew "z"
brew "zlib", link: true
brew "zoxide"
brew "d12frosted/emacs-plus/emacs-plus@29", args: ["with-modern-purple-flat-icon", "with-native-comp"]
brew "render-oss/render/render"
cask "affinity-designer"
cask "arc"
cask "bartender"
cask "chromium"
cask "cleanshot"
cask "daisydisk"
cask "dash"
cask "db-browser-for-sqlite"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "itsycal"
cask "ivpn"
cask "lunar"
cask "miniconda"
cask "obsidian"
cask "raycast"
cask "rectangle"
cask "signal"
cask "slack"
cask "steam"
cask "swiftformat-for-xcode"
cask "thonny"
cask "visual-studio-code"
cask "warp"
cask "zed"
cask "zoom"
mas "Dark Noise", id: 1465439395
mas "Flighty", id: 1358823008
mas "Hue in the Menu", id: 1534707384
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Strongbox", id: 1270075435
mas "Toggl Track", id: 1291898086
mas "Xcode", id: 497799835
