" Use jj to escape 
inoremap jj <ESC>
" Remap shortcut key
let mapleader = "\<Space>"
" Turn on Syntax Highlighting
syntax on
" Use utf-8 encoding
set encoding=utf-8
" Use 256 color palette
set t_Co=256
" Copy indentation level when creating a new line
set autoindent 
" Use system clipboard 
set clipboard=unnamed
" Intelligently indent
set smartindent
" Keep vim files in the ~/.vim folder
set viminfo='100,h,n~/.vim/viminfo'
" Case insensitive search
set ignorecase
" Unless there is mixed case, then make it case sensitive
set smartcase
" Highlight search terms
set hlsearch
" Highlight search terms as you type them
set incsearch
"Move around wrapped lines easier
nnoremap j gj
nnoremap k gk
"Enter command mode without shift key
nnoremap ; :
vnoremap ; :
" Use zenburn theme
colors zenburn
" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
let s:opam_share_dir = system("opam config var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if count(s:opam_available_tools, tool) > 0
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line
" ## added by OPAM user-setup for vim / ocp-indent ## 4f57f24953537bcfc86072851133b690 ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/Users/nishantjha/.opam/default/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## end of OPAM user-setup addition for vim / ocp-indent ## keep this line
